Repository internxt/drive-desktop, pull requests merged in 2025-02, with the labels that each got.

#547 [PB-3747]: Feat/antivirus UI
  .gitignore
  src/apps/main/main.ts
  src/apps/main/preload.d.ts
  src/apps/main/preload.js
  src/apps/renderer/assets/onboarding/backups-dark.svg
  src/apps/renderer/assets/onboarding/backups.svg
  src/apps/renderer/assets/onboarding/scanner-dark.svg
  src/apps/renderer/assets/onboarding/scanner.svg
  src/apps/renderer/context/AntivirusContext.tsx
  src/apps/renderer/hooks/antivirus/useAntivirus.tsx
  src/apps/renderer/localize/locales/en.json
  src/apps/renderer/localize/locales/es.json
  src/apps/renderer/localize/locales/fr.json
  src/apps/renderer/pages/Onboarding/config.tsx
  src/apps/renderer/pages/Onboarding/slides/AntivirusSlide.tsx
  src/apps/renderer/pages/Onboarding/slides/BackupsSlide.tsx
  src/apps/renderer/pages/Settings/Antivirus/components/ActionDialog.tsx
  src/apps/renderer/pages/Settings/Antivirus/index.tsx
  src/apps/renderer/pages/Settings/Antivirus/views/ChooseItemsState.tsx
  src/apps/renderer/pages/Settings/Antivirus/views/LockedState.tsx
  src/apps/renderer/pages/Settings/Antivirus/views/RemoveMalwareState.tsx
  src/apps/renderer/pages/Settings/Antivirus/views/ScanState.tsx
  src/apps/renderer/pages/Settings/Header.tsx
  src/apps/renderer/pages/Settings/index.tsx
Labels: enhancement

#554 [_]: feat/hide Antivirus
  package.json
  release/app/package.json
  src/apps/main/preload.d.ts
  src/apps/renderer/pages/Onboarding/config.tsx
  src/apps/renderer/pages/Settings/Header.tsx
  src/apps/renderer/pages/Settings/index.tsx
  src/apps/renderer/pages/Widget/Header.tsx
Labels: bug

#535 [_]: doc/new release instructions
  .erb/scripts/convert-hash.py
  README.md
Labels: documentation
